version: "2"
services:
  ui-components:
    image: openlmis/dev-ui:8.0.0-RC2
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
  image:
    build: .
    image: openlmis/ui-components
