FROM debian:jessie

WORKDIR /root
RUN apt-get update && apt-get install -y bash libfontconfig nodejs npm transifex-client git
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g bower grunt-cli phantomjs-prebuilt

WORKDIR /app
VOLUME ["/app"]

EXPOSE 9000
CMD npm install --no-optional && bower install --allow-root --config.interactive=false && bash