FROM debian:jessie

WORKDIR /root
RUN apt-get update && apt-get install -y bash libfontconfig npm transifex-client git curl

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g bower grunt-cli phantomjs-prebuilt

WORKDIR /app
VOLUME ["/app"]

EXPOSE 9000
CMD npm install --no-optional && bower install --allow-root --config.interactive=false && bash